version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    # image: mysql:8.0
    ports:
      - 3306:3306
    build:
      context: .
      args:
      - LANG=zh_CN.UTF-8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_Empty_PASSWORD: no

      # 自动创建名为 'docker' 的数据库，create database docker;
      MYSQL_DATABASE: docker
      # 自动创建数据库的普通用户 'test'
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      
    volumes:
      # 数据挂载
      # - ./mysql/data:/var/lib/mysql      
      - /home/xsj/go/src/github.com/sjxiang/dev_script/tmp/mysql:/var/lib/mysql   

    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci



  redis:
    container_name: redis
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes:
      - /home/xsj/go/src/github.com/sjxiang/dev_script/tmp/redis/data:/data
    command: redis-server --appendonly yes 
    
    # --requirepass 123456


  # mariadb:
  #   container_name: mariadb
  #   # image: mysql:5.7
  #   image: mariadb:10
  #   ports:
  #     - 3306:3306
  #   build:
  #     context: .
  #     args:
  #     - LANG=C.UTF-8
  #   environment:
  #     MARIADB_ROOT_PASSWORD: 123456
  #     MARIADB_ALLOW_Empty_PASSWORD: no

  #     # 自动创建名为 'docker' 的数据库，create database docker;
  #     MARIADB_DATABASE: docker
  #     # 自动创建数据库的普通用户 'test'
  #     MARIADB_USER: test
  #     MARIADB_PASSWORD: 123456
      
  #   volumes:
  #     # 数据挂载
  #     # - ./mysql/data:/var/lib/mysql      
  #     - /home/xsj/go/src/github.com/sjxiang/dev_script/tmp/mariadb:/var/lib/mariadb   

  #   command:
  #     --default-authentication-plugin=mysql_native_password
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci