app:
  name: Gohub
  port: 9090
  debug: false
  key: 3302145ugaidgiavbdUVSDIGI8uvdasivua
  app_url: http://localhost:9090
  timezone: Asia/Shanghai  
  
  # # app_sign_expire: 60
  # run_mode: dev
  # http_port: 9090
  # read_timeout: 60
  # write_timeout: 60
  # runtime_root_path: runtime/
  # app_log_path: logs/hub-api.log
  # app_key: aivbsodfb9SDIABFIaBSDIB
  # app_URL: http://localhost:9090

mysql:
  dbname: docker
  username: root
  password: 123456
  host: 172.18.0.2
  port: 3306
  charset: utf8mb4
  max_open_conn: 25
  max_idle_conn: 100
  conn_max_life_second: 30
  table_prefix: search_

redis:
  host: 127.0.0.1:6379
  db: 0
  password:
  min_idle_conn: 500
  pool_size: 100
  max_retries: 3
