app:
  name: Gohub
  port: 9090
  debug: false
  key: 3302145ugaidgiavbdUVSDIGI8uvdasivua
  app_url: http://localhost:9090
  timezone: Asia/Shanghai  
  env: local  # 可选有，local / testing / production
  

mysql:
  dbname: docker
  username: root
  password: 123456
  host: 172.18.0.3
  port: 3306
  charset: utf8mb4
  max_open_conn: 25
  max_idle_conn: 100
  conn_max_life_second: 30


redis:
  host: 172.18.0.2
  port: 6379
  db: 1
  password: 
