app:
  app_sign_expire: 60
  run_mode: dev
  http_port: 9090
  read_timeout: 60
  write_timeout: 60
  runtime_root_path: runtime/
  app_log_path: logs/hub-api.log

mysql:
  dbname: shop
  user: root
  password: root
  host: localhost:3306
  max_open_conn: 1000
  max_idle_conn: 100
  conn_max_life_second: 30
  table_prefix: search_

redis:
  host: 127.0.0.1:6379
  db: 0
  password:
  min_idle_conn: 500
  pool_size: 100
  max_retries: 3
